### ISSUE TITLE
emit(...) as a generator?

### ISSUE THREAD

**Issue by fearthecowboy** [aleclarson/ee-ts#41]
So I was thinking about events with multiple listeners, and I have a use case where I need the results back from all of them

I'm wondering what you think about turning the `emit` result into an `Iterable<EventOut<T,K>>`  and making it a generator function.

Either that, or make a second `emit` that does that (`emitWithResults`?). (since, it's pretty much a breaking change otherwise)

**Comment by aleclarson** [comment]
The `listeners` method was made for that use case. :)
```js
// Using for..of
const results: any[] = []
for (const fn of ee.listeners('test')) {
  results.push(fn())
}

// Using Array.from
const results = Array.from(ee.listeners('test'), fn => fn())
```

**Comment by fearthecowboy** [comment]
Aha! 

That's helpful ... I completely missed that one.  

 That means that I have to iterate over the listeners and still call each one with the parameters. 

I guess I'll just make a helper method for that, since I have to do that alot.
